import "@/src/app/globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Seovileo-website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <main className="text-p mx-auto max-h-screen overflow-hidden px-4">
        {children}
      </main>
    </div>
  );
}
