import "@/src/app/globals.css";
import { inter } from "@/src/ui/fonts";
import type { Metadata } from "next";
import dynamic from "next/dynamic";

import Header from "../ui/header/Header";
const ScrollUp = dynamic(() => import("@/src/ui/buttons/ScrollUp"));
const Footer = dynamic(() => import("@/src/ui/footer/Footer"));

export const metadata: Metadata = {
  title: "Seovileo-website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">
      <head>
        <meta name="theme-color" content="#141414" />
      </head>
      <body className={`${inter.className}`}>
        <Header />
        <main className="text-p mx-auto min-h-screen max-w-screen-2xl px-4">
          {children}
        </main>
        <ScrollUp />
        <Footer />
      </body>
    </html>
  );
}
